### ISSUE TITLE
What cha doing here? Friend.

### ISSUE THREAD

**Issue by 4-Leafs-Code** [sugam-pokhrel/community_classroom_practice#1]
I was just curious as to what you are going to be making with this community classroom? I'm currently building the Prisoner Reentry Advocates website with FearlessTech but I want to build a secure platform for colleges to offer prisoners tech degrees. 

This caught my attention because it  might be the type of project FearlessTech works on and it might be good practice for my college platform.

**Comment by sugam-pokhrel** [comment]
I'm not making anything for now just i was trying something....Community classroom was started by a tech you-tuber where he taught some data structures so i thought like joining it  for learning something...This community help others to start their coding journey......Glad you were intrested

**Comment by 4-Leafs-Code** [comment]
Yeah! I 've only been programming for about 10 months and these things help. That's why I started FearlessTech. People have grate ideas but do not have the skills to complete the project. This way everyone is working together, learning, and teaching. I thought I was smart until I started playing with people on GitHub. 😃 But even still I've thought these old heads thing or 2. 

Are you saying community classroom is a repo or org? Could I please have the link?

**Comment by sugam-pokhrel** [comment]
I really liked you initiative and I will be joining your FearlessTech...https://github.com/WeMakeDevs this their account I think the have closed coz I cannot  open their website.... I would be really happy to contribute from my side........ I'm also a newbie tryin to get experiences..Any help and suggestion form you will be helpful...

**Comment by 4-Leafs-Code** [comment]
https://github.com/4-Leafs-Code/MyBookMarks check out "the secret book of secret knowledge" but there are a lot of grate sites here. Mostly, don't just do tutorials, build something or continue building it after the tutorial. Reentry was a linkedin clone when I started.  I'm so glad your going to come help out. Even if something not posted as an issue run the site and if you see something you can improve, even the smallest css adjustment, have at it. If you just need a little help make an issue or go into a discussion and @ me or one of my co-owners. Just don't quit because you you are afraid to ask because were all more then happy to help it helps us learn too.

If your earning some kind of tech degree I'd suggest joining: https://education.github.com/
There are alot of good/free benefits but my favorite part is the community exchange. This is how I found contributors for the reentry repo but there are alot of projects on their for people to practice on. 
https://goodfirstissues.com/index.html there is this site and one just like it for help wanted I can not find the link to at this second. Sometimes I just crawl threw the post and even if I don't know the language I will comment my thoughts on the problem. I need to add these to my bookmarks actually. 

I'm just hunting for our next project. I'm hoping to find one like I was hoping this was.
